name: portfolio_app
description: "A futuristic portfolio app with a cosmic home page."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  particles_flutter: ^0.1.4
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/my_picture.jpg
    - assets/project1.jpg
    - assets/project2.jpg
    - assets/project3.jpg
    - assets/project4.jpg
    - assets/cover1.jpg
    - assets/cover2.jpg
    - assets/cover3.jpg
    - assets/cover4.jpg
